### ISSUE TITLE
Blurry fonts when embedded at larger breakpoints. 

### ISSUE THREAD

**Issue by dopry** [spry-group/coclear-cdp#1]
When looking at http://www.coclear.co/cdp-data-visualization when > 1280px wide the text becomes blurry. I suspect the upscaling in https://github.com/spry-group/coclear-cdp/blob/8056a326d4af4c84ae4719a2e935dafcbf5b6ffa/embed.css#L52 to be at fault. 

Can we try to improve font rendering at his breakpoint? Is there a better approach to responsiveness for content embedded in an iFrame?

**Comment by Klemensas** [comment]
This is quite a pesky problem related to scaling. With chrome being the main offender.
There's a variety of css rules proposed to circumvent the blurriness, but none that I've tried work consistently.

Alternatives are either switching to zoom or to padding method https://getbootstrap.com/docs/4.1/utilities/embed/
But these require the content inside the iframe itself being responsive which doesn't seem to be the case here.

**Comment by dopry** [comment]
What would be involved in updating to a responsive iframe? This is going to get pretty wide exposure and has our name on it. I'd like it to be a good reflection of our workmanship.

**Comment by dopry** [comment]
resolved by eliminating embeds.
