### ISSUE TITLE
Setup CircleCI to update the data when it changes.

### ISSUE THREAD

**Issue by dopry** [spry-group/coclear-cdp#10]
see: https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow
we need to schedule npm run update-data to run regularly and commit and push an update to the REPO if the data has changed.

alternatively, we could use a cronjob, but I'd like to start getting this stuff all moved into CI eliminating our dependence on stand-alone servers.

1 hour frequency initially.

**Comment by andyzickler** [comment]
Found some small issues that need fixing. I used the wrong quotes for the commit message and so `date` is not being executed, I think i'll just remove that. Commits have a date stamp anyway. Also when circle ci does not update it marks the current commit failed. I'm sure there's a flag somewhere to disable that.
