### ISSUE TITLE
Misplaced lines in popups on iPad/Chrome

### ISSUE THREAD

**Issue by dopry** [spry-group/coclear-cdp#2]
We viewing popups on an iPad with chrome there are out of place lines in the pop-up legend. They should not appear here. Please make sure they don't show up. 

![image](https://user-images.githubusercontent.com/387640/50798284-d8efaa80-12a5-11e9-821f-dba28129c647.png)

**Comment by andyzickler** [comment]
If this is on iPad it's not actually a Chrome issue as all browsers on iOS use WebKit for rendering.

I don't have an iPad to try so I used the iPad simulator. I wasn't able to fully recreate the issue, however I did get a similar artifact:

<img width="588" alt="screen shot 2019-01-07 at 6 31 42 pm" src="https://user-images.githubusercontent.com/1017095/50799654-e8252700-12aa-11e9-9b57-c1bbf11decfe.png">

I found some (old) discussion about `opacity` and `z-index` causing rendering bugs. https://stackoverflow.com/questions/15558148/possible-opacity-z-index-bug That suggested trying a  workaround of using `background-color: rgba(255, 255, 255, .9)` Setting that on `#toolbar` and on `#tooltip .stats`

<img width="600" alt="screen shot 2019-01-07 at 6 31 07 pm" src="https://user-images.githubusercontent.com/1017095/50799757-6386d880-12ab-11e9-9cad-8c5f20d6ea77.png">

*If* this solves the problem, we'll need to make a few more tweaks to the colors to match the original.

**Comment by dopry** [comment]
Sally provided some additional debugging information.


> * Interestingly, the dv text is now clear on my ipad in chrome as well as safari.
> * I checked on two ipad Pros.  (mine which is about 4 years old and Steve's which is the latest Ipad Pro.  
> * On my ipad Pro the line issue is not currently visible in Safari Version 12.0
> * On the latest ipad Pro the line issue is visible in Safari Version 12.1.1 
> * The version of Chrome we both have is 71 on iOS12.1. The lines are visible in Chrome on both ipads

**Comment by dopry** [comment]
resolved by eliminating embeds.
