### ISSUE TITLE
Responsive Tweaks: Legend at medium widths. 

### ISSUE THREAD

**Issue by dopry** [spry-group/coclear-cdp#8]
At some breaks points legends single column while selects are two column.   Let's make the legends a 2 column layout at these breakpoints to preserve space. 

![image](https://user-images.githubusercontent.com/387640/51754775-2e400000-208b-11e9-9f42-a1aa084a7bcf.png)

**Comment by Klemensas** [comment]
Done in https://github.com/spry-group/coclear-cdp/commit/5af77a8019b51003567bf446288b5244ea5df77a

**Comment by dopry** [comment]
Looks great! Thanks!
